### ISSUE TITLE
Pas de bloc de skins

### ISSUE THREAD

**Issue by ClementRmc** [Seblor/wp-mc-skin-viewer#1]
Hello !

J'ai installé ton plugin sur mon wordpress et je l'ai activé, toutefois une fois dans l'édition d'article je ne vois pas le bloc permettant d'entrer l'url du skin.

Je suis sous wordpress 5.7.1 et PHP 7.4.5.

Merci d'avance pour ton aide :)

**Comment by Seblor** [comment]
Hello,

I made this plugin mainly to test how wordpress plugins work. Unfortunately, I'm really not a fan of PHP development and the wordpress API.

I do not wish to provide continued support for the current Wordpress version, and I do not intend to do any more work on this repository for the foreseeable future.

However I welcome and will review any PR.

**Comment by ClementRmc** [comment]
D'accord dommage, merci quand même pour ta réponse.
