### ISSUE TITLE
How to use 

### ISSUE THREAD

**Issue by Kemilab** [Seblor/wp-mc-skin-viewer#2]
Hi, I'm bit confused. Idk how to add my skin to my website. For editor I use Elementor. But there seems to be no + or skin icon. Do i need to use something else?
 Thanks in advance

**Comment by Seblor** [comment]
Hey there,

No idea how to implement the button on the new Wordpress editor, and do not plan to add it for now. But I welcome any PR.

**Comment by Seblor** [comment]
Dup of #1
